version: '3'

services:

  paideia-state:
    container_name: paideia-state
    image: paideia-state:latest
    env_file: .env
    volumes:
      - ./transaction_archive:/opt/docker/transaction_archive
      - ./errors:/opt/docker/errors
      - ./stakingStates:/opt/docker/stakingStates
      - ./daoconfigs:/opt/docker/daoconfigs
      - ./proposals:/opt/docker/proposals
    ports:
      - 9123:9000
    networks:
      - p-net
    restart: unless-stopped

networks:
  p-net:
    external: true
